### ISSUE TITLE
missing zspmv_openmp.cpp in 4.5.0 tarball

### ISSUE THREAD

**Issue by GianlucaBertaina** [qutip/qutip.github.io#111]
The tarball at http://qutip.org/downloads/4.5.0/qutip-4.5.0.tar.gz does not contain the file qutip/cy/openmp/src/zspmv_openmp.cpp which is needed when installing qutip with the --with-openmp option.

If I copy such file from https://github.com/qutip/qutip/blob/qutip-4.5.X/qutip/cy/openmp/src/zspmv_openmp.cpp then installation works fine.

**Comment by GianlucaBertaina** [comment]
@nathanshammah Sorry to bother you but I think this is important

**Comment by nathanshammah** [comment]
Thank you @GianlucaBertaina. Maybe @ajgpitch or @Ericgig can help?

**Comment by nathanshammah** [comment]
Second ping to @ajgpitch @Ericgig @jakelishman @hodgestar, as I am not knowledgeable about it.

**Comment by jakelishman** [comment]
This is not really any different to if there had been a bug in the code in 4.5.0.  We wouldn't fix that by amending the 4.5.0 release, we'd fix it by making a new bugfix release (like 4.5.1) instead.  Things like PyPI wouldn't let us upload a "new" version of 4.5.0, because it doesn't know that users aren't relying on the buggy behaviour, so it won't let us rewrite history.  In the end, this is fixed in `master`, and the fix was distributed as part of 4.6.0.  We _could_ release a new version 4.5.4 with the fix as well, but then the question is "why does this bug get special treatment, but others don't?" - we've never backported bugfixes to old versions before, and we only support one minor release at a time.

We _can_ fix it, but especially now with the 4.6 branch released and the full 4.5.x release methods being slow and annoying, it might not really be worth it.  If we eschewed the proper release methods and just hotfixed the tarball, qutip.org would be out of sync with the GitHub release page, pip, and conda, which isn't really ideal either.

**Comment by hodgestar** [comment]
@GianlucaBertaina Sorry about leaving out the file and about taking ages to reply to this. Thank you for letting us know and we'll try respond more promptly in the future (we have a bigger team of core contributors now and a much more automated release process).

Can you upgrade to 4.6.2 (or maybe you have already given the delay)?

**Comment by GianlucaBertaina** [comment]
I perfectly understand that it is not worth the effort to make a bugfix release for 4.5 just for this bug, especially since there's now the 4.6 branch. Moreover, the bug is easily fixable by copying a file. 
I plan to update to 4.6 soon. Feel free to close this issue.
Thanks for this great software!

**Comment by hodgestar** [comment]
@GianlucaBertaina Pleasure! Thank you again for reporting the issue.
