### ISSUE TITLE
Fix the tutorials page layout

### ISSUE THREAD

**Issue by quantshah** [qutip/qutip.github.io#150]
After merging #149 I noticed that the tutorials page layout got completely haywire - https://qutip.org/tutorials.html.  @BoxiLi Could you have a quick look how we can fix that? Specifically the parts about PIQS and the lectures are pushed below.

**Comment by jakelishman** [comment]
Your problem is here: https://github.com/qutip/qutip.github.io/blob/52861cc40e461336aeccc2d6fd0d18824fd84240/tutorials.html#L157-L179

Two extra closing `div` tags have been copied in (intended to close a row), but the opening ones are missing.  Either move the `h4` and `ul` into a pre-existing row (and remove the closing `div`s), or add in the necessary opening divs.
